import org.aspectj.bridge.IMessage
import org.aspectj.bridge.MessageHandler
import org.aspectj.tools.ajc.Main

apply plugin: 'com.android.library'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.aspectj:aspectjtools:1.9.21'
        classpath 'org.aspectj:aspectjweaver:1.9.21'
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.aspectj:aspectjrt:1.9.21'
    androidTestImplementation 'androidx.test:core:1.5.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
}

android {
    namespace 'gradlebuild.lining.com.aspectlib'
    compileSdk 35
    buildToolsVersion "35.0.0"

    lint {
        abortOnError false
    }
}

android.libraryVariants.all { variant ->
    def proj = project
    def javaCompile = variant.javaCompileProvider.get()
    javaCompile.doLast {
        String[] args = ["-showWeaveInfo",
                         "-1.8",
                         "-inpath", javaCompile.destinationDirectory.get().asFile.toString(),
                         "-aspectpath", javaCompile.classpath.asPath,
                         "-d", javaCompile.destinationDirectory.get().asFile.toString(),
                         "-classpath", javaCompile.classpath.asPath,
                         "-bootclasspath", proj.android.bootClasspath.join(File.pathSeparator)]
        def log = proj.logger
        log.debug "ajc args: " + Arrays.toString(args)
        MessageHandler handler = new MessageHandler(true)
        new Main().run(args, handler)
        for (IMessage message : handler.getMessages(null, true)) {
            switch (message.getKind()) {
                case IMessage.ABORT:
                case IMessage.ERROR:
                case IMessage.FAIL:
                    log.error message.message, message.thrown
                    break
                case IMessage.WARNING:
                case IMessage.INFO:
                    log.info message.message, message.thrown
                    break
                case IMessage.DEBUG:
                    log.debug message.message, message.thrown
                    break
            }
        }
    }
}
